name: BungeePerms
main: net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin
version: '${build.fullversion.resource}'
author: [wea_ondara, AuroraRainbow]
load: startup
api-version: '1.13'

softdepend: [PlaceholderAPI, Vault, WorldEdit, AsyncWorldEdit, FastAsyncWorldEdit, Essentials]

commands:
    bungeepermsbukkitbridge:
        description: base command
        aliases: bpbb
    bungeepermsbukkitbridge reload:
        description: reinjects Bungeeperms into all found/supported plugins
        
